### ISSUE TITLE
[Django 1.9.2] ImportError: No module named importlib

### ISSUE THREAD

**Issue by anatskiy** [arkanister/django-flickr-gallery#11]
I do everything according to the instruction but in the step 6 I get the following error:

```
Traceback (most recent call last):
  File "/Users/evgeny/Projects/nva/env/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/Users/evgeny/Projects/nva/env/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 116, in inner_run
    self.check(display_num_errors=True)
  File "/Users/evgeny/Projects/nva/env/lib/python2.7/site-packages/django/core/management/base.py", line 426, in check
    include_deployment_checks=include_deployment_checks,
  File "/Users/evgeny/Projects/nva/env/lib/python2.7/site-packages/django/core/checks/registry.py", line 75, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/Users/evgeny/Projects/nva/env/lib/python2.7/site-packages/django/core/checks/urls.py", line 10, in check_url_config
    return check_resolver(resolver)
  File "/Users/evgeny/Projects/nva/env/lib/python2.7/site-packages/django/core/checks/urls.py", line 19, in check_resolver
    for pattern in resolver.url_patterns:
  File "/Users/evgeny/Projects/nva/env/lib/python2.7/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/evgeny/Projects/nva/env/lib/python2.7/site-packages/django/core/urlresolvers.py", line 417, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/evgeny/Projects/nva/env/lib/python2.7/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/evgeny/Projects/nva/env/lib/python2.7/site-packages/django/core/urlresolvers.py", line 410, in urlconf_module
    return import_module(self.urlconf_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/evgeny/Projects/nva/wui/urls.py", line 26, in <module>
    url(r'^gallery/', include('django_flickr_gallery.urls')),
  File "/Users/evgeny/Projects/nva/env/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 52, in include
    urlconf_module = import_module(urlconf_module)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/evgeny/Projects/nva/env/lib/python2.7/site-packages/django_flickr_gallery/urls.py", line 4, in <module>
    from django_flickr_gallery.utils.import_tools import load_view
  File "/Users/evgeny/Projects/nva/env/lib/python2.7/site-packages/django_flickr_gallery/utils/import_tools.py", line 2, in <module>
    from django.utils.importlib import import_module
ImportError: No module named importlib
```

This is the reason why: [link](https://bitbucket.org/lgs/djangosaml2/issues/40/django-19-deprecates-djangoutilsimportlib)

**Comment by arkanister** [comment]
Fixed `import_module` import.

Changed to `from importlib import import_module`.
